/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package universidadg6.vistas;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import universidadg6.accesoadatos.AlumnoData;
import universidadg6.accesoadatos.InscripcionData;
import universidadg6.accesoadatos.MateriaData;
import universidadg6.entidades.Alumno;
import universidadg6.entidades.Materia;

/**
 *
 * @author Familia
 */
public class Inscripciones extends javax.swing.JInternalFrame {
private Connection con;
private ArrayList<Alumno> alu;
private ArrayList<Materia> listam;
private InscripcionData idata;
private AlumnoData adata;
private MateriaData mdata;
private DefaultTableModel modelo;
    public Inscripciones() {
        initComponents();
        adata = new AlumnoData();
        idata = new InscripcionData();
        alu = (ArrayList<Alumno>)adata.listaAlumnos();     
        modelo = new DefaultTableModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRinscriptas = new javax.swing.JRadioButton();
        jRnoinscripta = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTmateria = new javax.swing.JTable();
        jBinscribir = new javax.swing.JButton();
        jBanular = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCBAlumno = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de inscripcion");

        jLabel2.setText("Selecciona un alumno: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Listado de Materias");

        jRinscriptas.setText("Materia inscriptas");
        jRinscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRinscriptasActionPerformed(evt);
            }
        });

        jRnoinscripta.setText("Materias no inscriptas");

        jTmateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTmateria);

        jBinscribir.setText("Inscribir");
        jBinscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinscribirActionPerformed(evt);
            }
        });

        jBanular.setText("Anular inscripcion");

        jButton3.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jRinscriptas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRnoinscripta)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBinscribir)
                                    .addGap(78, 78, 78)
                                    .addComponent(jBanular)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRinscriptas)
                    .addComponent(jRnoinscripta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBinscribir)
                    .addComponent(jBanular)
                    .addComponent(jButton3))
                .addGap(0, 38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRinscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRinscriptasActionPerformed
        // TODO add your handling code here:
        
       BorrarFilaTabla();
       jRnoinscripta.setSelected(false);
       
       CargarDatosInscriptas();
      jBanular.setEnabled(true);     
      jBinscribir.setEnabled(false);
    }//GEN-LAST:event_jRinscriptasActionPerformed

    private void jBinscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinscribirActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jBinscribirActionPerformed

    public void CargarAlumnos(){
        for (Alumno a : alu ) {
            jCBAlumno.addItem(a);
            
        }
    }
    
    public void ArmarCabecera (){
        ArrayList <Object> FilaCabecera = new ArrayList <>();
        FilaCabecera.add( "ID");
        FilaCabecera.add("Nombre");
        FilaCabecera.add("Año");
        for (Object object : FilaCabecera) {
            modelo.addColumn(object);           
        }
        jTmateria.setModel(modelo);
        
    }
    
    public void BorrarFilaTabla(){

           int indice = modelo.getRowCount() -1;
           for (int i = indice; i >= 0; i--) {
               modelo.removeRow(i);
           }

       }
     public void CargarDatosNoInscriptas (){
         //BorrarFilaTabla();
         Alumno selec = (Alumno)jCBAlumno.getSelectedItem();
         listam = (ArrayList)idata.obtenerMateriaNoCursadas(selec.getIdAlumno());
         for (Materia m : listam ) {
             modelo.addRow(new Object[] {m.getIdMateria(),m.getNombre(),m.getAnioMateria()}  );
         }
         }
    public void CargarDatosInscriptas(){
         //BorrarFilaTabla();
        Alumno select =(Alumno)jCBAlumno.getSelectedItem();
        List <Materia> Lista =(ArrayList)idata.obtenerMateriaCursadas(select.getIdAlumno());
        for (Materia object : Lista) {
            modelo.addRow(new Object[] {object.getAnioMateria(), object.getIdMateria(),object.getNombre()} );
            
        }
             
     }
    
    
    
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBanular;
    private javax.swing.JButton jBinscribir;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<Alumno> jCBAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRinscriptas;
    private javax.swing.JRadioButton jRnoinscripta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTmateria;
    // End of variables declaration//GEN-END:variables
}
